// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CreateBlogTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createBlog() {
    driver.get("https://it-314-g6-blogging-platform.vercel.app/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.cssSelector(".Home_writeButton__LBl6W")).click();
    driver.findElement(By.cssSelector(".ql-bubble p")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ql-bubble > .ql-editor"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Test Blog</p>'}", element);
    }
    driver.findElement(By.cssSelector(".ql-blank > p")).click();
    driver.findElement(By.cssSelector(".p-6:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".ql-snow > .ql-editor")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ql-snow > .ql-editor"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Small Normal Large Huge</p><p>Sans Serif MonoSpace</p><p>Bold Italic Underline Strikethrough</p>'}", element);
    }
    driver.findElement(By.cssSelector(".ql-size > .ql-picker-label")).click();
    driver.findElement(By.cssSelector("#ql-picker-options-1 > .ql-picker-item:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".ql-snow p:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".ql-snow p:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".ql-snow p:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ql-snow > .ql-editor"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p><span class=\"ql-size-small\">Small</span> Normal Large Huge</p><p>Sans Serif MonoSpace</p><p>Bold Italic Underline Strikethrough</p>'}", element);
    }
    driver.findElement(By.cssSelector(".ql-size > .ql-picker-label")).click();
    driver.findElement(By.cssSelector("#ql-picker-options-1 > .ql-picker-item:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".ql-snow p:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ql-snow > .ql-editor"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p><span class=\"ql-size-small\">Small</span> Normal <span class=\"ql-size-large\">Large</span> Huge</p><p>Sans Serif MonoSpace</p><p>Bold Italic Underline Strikethrough</p>'}", element);
    }
    driver.findElement(By.cssSelector(".ql-size > .ql-picker-label")).click();
    driver.findElement(By.cssSelector("#ql-picker-options-1 > .ql-picker-item:nth-child(4)")).click();
    driver.findElement(By.cssSelector("p:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ql-snow > .ql-editor"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p><span class=\"ql-size-small\">Small</span> Normal <span class=\"ql-size-large\">Large</span> <span class=\"ql-size-huge\">Huge</span></p><p>Sans Serif MonoSpace</p><p>Bold Italic Underline Strikethrough</p>'}", element);
    }
    driver.findElement(By.cssSelector(".ql-font > .ql-picker-label")).click();
    driver.findElement(By.cssSelector("#ql-picker-options-0 > .ql-picker-item:nth-child(2)")).click();
    driver.findElement(By.cssSelector("p:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ql-snow > .ql-editor"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p><span class=\"ql-size-small\">Small</span> Normal <span class=\"ql-size-large\">Large</span> <span class=\"ql-size-huge\">Huge</span></p><p>Sans <span class=\"ql-font-serif\">Serif</span> MonoSpace</p><p>Bold Italic Underline Strikethrough</p>'}", element);
    }
    driver.findElement(By.cssSelector(".ql-font > .ql-picker-label")).click();
    driver.findElement(By.cssSelector("#ql-picker-options-0 > .ql-picker-item:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".ql-snow > .ql-editor")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ql-snow > .ql-editor"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p><span class=\"ql-size-small\">Small</span> Normal <span class=\"ql-size-large\">Large</span> <span class=\"ql-size-huge\">Huge</span></p><p>Sans <span class=\"ql-font-serif\">Serif</span> <span class=\"ql-font-monospace\">MonoSpace</span></p><p>Bold Italic Underline Strikethrough</p>'}", element);
    }
    driver.findElement(By.cssSelector(".ql-formats:nth-child(4) > .ql-bold > svg")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ql-formats:nth-child(4) > .ql-bold > svg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("p:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ql-snow > .ql-editor"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p><span class=\"ql-size-small\">Small</span> Normal <span class=\"ql-size-large\">Large</span> <span class=\"ql-size-huge\">Huge</span></p><p>Sans <span class=\"ql-font-serif\">Serif</span> <span class=\"ql-font-monospace\">MonoSpace</span></p><p><strong>Bold</strong> Italic Underline Strikethrough</p>'}", element);
    }
    driver.findElement(By.cssSelector(".ql-formats:nth-child(4) .ql-stroke:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ql-formats:nth-child(4) .ql-stroke:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("p:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ql-snow > .ql-editor"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p><span class=\"ql-size-small\">Small</span> Normal <span class=\"ql-size-large\">Large</span> <span class=\"ql-size-huge\">Huge</span></p><p>Sans <span class=\"ql-font-serif\">Serif</span> <span class=\"ql-font-monospace\">MonoSpace</span></p><p><strong>Bold</strong> <em>Italic</em> Underline Strikethrough</p>'}", element);
    }
    driver.findElement(By.cssSelector(".ql-formats:nth-child(4) > .ql-underline > svg")).click();
    driver.findElement(By.cssSelector("p:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ql-snow > .ql-editor"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p><span class=\"ql-size-small\">Small</span> Normal <span class=\"ql-size-large\">Large</span> <span class=\"ql-size-huge\">Huge</span></p><p>Sans <span class=\"ql-font-serif\">Serif</span> <span class=\"ql-font-monospace\">MonoSpace</span></p><p><strong>Bold</strong> <em>Italic</em> <u>Underline </u>Strikethrough</p>'}", element);
    }
    driver.findElement(By.cssSelector(".ql-formats:nth-child(4) > .ql-strike .ql-fill:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ql-snow > .ql-editor"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p><span class=\"ql-size-small\">Small</span> Normal <span class=\"ql-size-large\">Large</span> <span class=\"ql-size-huge\">Huge</span></p><p>Sans <span class=\"ql-font-serif\">Serif</span> <span class=\"ql-font-monospace\">MonoSpace</span></p><p><strong>Bold</strong> <em>Italic</em> <u>Underline </u><s>Strikethrough</s></p>'}", element);
    }
    driver.findElement(By.id("hashtags")).click();
    driver.findElement(By.cssSelector(".font-semibold:nth-child(1)")).click();
    assertThat(driver.switchTo().alert().getText(), is("Draft saved successfully!"));
  }
}
