// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class EditDraftTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void editDraft() {
    driver.get("https://it-314-g6-blogging-platform.vercel.app/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.cssSelector(".justify-center")).click();
    driver.findElement(By.cssSelector(".fa-user > path")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".fa-user > path"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".block:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".block:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Continue editing")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector("p:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ql-snow > .ql-editor"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Small Normal Large Huge</p><p>Sans Serif MonoSpace</p><p><strong>Bold</strong> <em>Italic</em> <u>Underline </u>Strikethrough</p><p>Editted the draft</p><p>Edit Successful</p>'}", element);
    }
    driver.findElement(By.cssSelector(".font-semibold:nth-child(1)")).click();
  }
}
