// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HashtagsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void hashtags() {
    driver.get("https://it-314-g6-blogging-platform.vercel.app/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.cssSelector(".fa-user > path")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".fa-user > path"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".block:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".block:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    js.executeScript("window.scrollTo(0,133.60000610351562)");
    driver.findElement(By.linkText("Continue editing")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.id("hashtags")).click();
    driver.findElement(By.id("hashtags")).sendKeys("hashtag");
    driver.findElement(By.cssSelector(".mb-4 > .px-4")).click();
    driver.findElement(By.id("hashtags")).click();
    driver.findElement(By.id("hashtags")).sendKeys("draft");
    driver.findElement(By.cssSelector(".mb-4 > .px-4")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mb-4 > .px-4"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("hashtags")).click();
    driver.findElement(By.id("hashtags")).sendKeys("remhashtag");
    driver.findElement(By.cssSelector(".mb-4 > .px-4")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mb-4 > .px-4"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".bg-blue-100:nth-child(3) path")).click();
    driver.findElement(By.cssSelector(".font-semibold:nth-child(1)")).click();
  }
}
