// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegisterTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void register() {
    driver.get("https://it-314-g6-blogging-platform.vercel.app/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.cssSelector(".fa-user")).click();
    driver.findElement(By.cssSelector(".block")).click();
    driver.findElement(By.linkText("Sign up")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("User1");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("testuser2@gmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("123456");
    driver.findElement(By.cssSelector(".p-3")).click();
    driver.findElement(By.cssSelector(".border-gray-300")).click();
    driver.findElement(By.cssSelector(".border-gray-300")).sendKeys("User1.#");
    driver.findElement(By.cssSelector("div:nth-child(2) > .block:nth-child(2)")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > .block:nth-child(2)")).sendKeys("20");
    driver.findElement(By.cssSelector(".resize-none")).click();
    driver.findElement(By.cssSelector(".resize-none")).sendKeys("Engineer");
    driver.findElement(By.cssSelector("div:nth-child(4) > .relative > .block")).click();
    driver.findElement(By.cssSelector("div:nth-child(4) > .relative > .block")).sendKeys("Location,Country");
    driver.findElement(By.cssSelector("div:nth-child(5) > .relative > .block")).click();
    driver.findElement(By.cssSelector("div:nth-child(5) > .relative > .block")).sendKeys("Technology");
    driver.findElement(By.cssSelector(".py-4")).click();
    js.executeScript("window.scrollTo(0,0)");
  }
}
